import { RizqGate, Reward, Challenge } from './types';

export const getRizqGatesData = (lang: 'id' | 'en'): RizqGate[] => [
  {
    id: 'syukur',
    name: lang === 'id' ? 'Syukur' : 'Gratitude',
    emoji: '🙏',
    description: lang === 'id' ? 'Rezeki melalui rasa syukur. Allah berjanji akan menambah nikmat bagi hamba-Nya yang bersyukur.' : 'Rezeki through gratitude. Allah promises to increase the blessings for those who are thankful.',
    dalil: lang === 'id' ? '“Sesungguhnya jika kamu bersyukur, pasti Kami akan menambah (nikmat) kepadamu..." (QS. Ibrahim: 7)' : '“If you are grateful, I will surely increase you [in favor]..." (Quran 14:7)',
    kisah: lang === 'id' ? 'Kisah Nabi Sulaiman AS yang dianugerahi kerajaan dan kekuasaan yang luar biasa, namun beliau selalu menunjukkan rasa syukur kepada Allah.' : 'The story of Prophet Sulaiman (Solomon) who was given immense kingdom and power, yet always showed gratitude to Allah.',
    color: 'emerald',
    amalan: [
      { id: 'syukur1', name: lang === 'id' ? 'Ucapkan "Alhamdulillah" 33x' : 'Say "Alhamdulillah" 33x', description: lang === 'id' ? 'Setiap selesai shalat fardhu.' : 'After each of the 5 daily prayers.' },
      { id: 'syukur2', name: lang === 'id' ? 'Refleksi 3 Nikmat' : 'Reflect on 3 blessings', description: lang === 'id' ? 'Tuliskan 3 hal spesifik yang kamu syukuri hari ini.' : 'Write down three specific things you are grateful for today.' },
      { id: 'syukur3', name: lang === 'id' ? 'Berterima Kasih' : 'Thank someone', description: lang === 'id' ? 'Sampaikan rasa terima kasih yang tulus kepada seseorang yang membantumu.' : 'Express genuine gratitude to a person who helped you.' },
      { id: 'syukur4', name: 'Sujud Syukur', description: lang === 'id' ? 'Sujud syukur atas nikmat yang tak terduga.' : 'Perform the prostration of gratitude for an unexpected blessing.' },
    ],
    dos: lang === 'id' ? ["Mengingat nikmat saat bangun tidur", "Menggunakan nikmat untuk kebaikan", "Berterima kasih kepada orang lain", "Melihat orang yang 'di bawah' kita"] : ["Remembering blessings upon waking up", "Using blessings for good", "Thanking others", "Looking at those 'below' us"],
    donts: lang === 'id' ? ["Mengeluh tentang hal-hal kecil", "Merasa iri dengan nikmat orang lain", "Lupa bahwa semua datang dari Allah", "Kufur nikmat"] : ["Complaining about small things", "Envying others' blessings", "Forgetting all comes from Allah", "Being ungrateful"],
    skillBooster: [{ title: lang === 'id' ? "Latihan Jurnal Syukur" : "Gratitude Journaling", description: lang === 'id' ? "Setiap malam, tulis 5 hal baru yang kamu syukuri hari ini, sekecil apapun itu." : "Every night, write down 5 new things you are grateful for today, no matter how small." }],
    reflectionPrompt: lang === 'id' ? "Nikmat apa yang sering saya lupakan untuk syukuri hari ini?" : "What blessing did I often forget to be grateful for today?"
  },
  {
    id: 'usaha',
    name: lang === 'id' ? 'Usaha & Ikhtiar' : 'Effort & Work',
    emoji: '💼',
    description: lang === 'id' ? 'Rezeki melalui kerja keras yang etis. Islam mendorong mencari nafkah lewat jalan yang halal.' : 'Rezeki through diligent and ethical work. Islam encourages seeking sustenance through lawful means.',
    dalil: lang === 'id' ? '"Dan bahwasanya seorang manusia tiada memperoleh selain apa yang telah diusahakannya." (QS. An-Najm: 39)' : '"And that there is not for man except that [good] for which he strives." (Quran 53:39)',
    kisah: lang === 'id' ? 'Kisah inspiratif Abdurrahman bin Auf yang datang ke Madinah tanpa harta. Beliau memulai dari pasar dan menjadi salah satu pedagang tersukses sambil tetap dermawan.' : 'The inspiring story of Abdurrahman bin Auf, who arrived in Medina as a poor immigrant. He started in the marketplace and became one of the most successful merchants while remaining generous.',
    color: 'sky',
    amalan: [
      { id: 'usaha1', name: lang === 'id' ? 'Tentukan Target Kerja' : 'Define a clear work goal', description: lang === 'id' ? 'Tetapkan satu target spesifik dan terukur untuk pekerjaanmu hari ini.' : 'Set one specific, measurable goal for your work/business today.' },
      { id: 'usaha2', name: lang === 'id' ? 'Pelajari Skill Baru' : 'Learn a new skill', description: lang === 'id' ? 'Luangkan minimal 15 menit untuk mempelajari sesuatu yang meningkatkan kualitas kerjamu.' : 'Spend at least 15 minutes learning something to improve your work.' },
      { id: 'usaha3', name: lang === 'id' ? 'Transaksi Jujur' : 'Make an honest transaction', description: lang === 'id' ? 'Pastikan semua urusanmu hari ini dilakukan dengan adil dan jujur.' : 'Ensure all your dealings today are fair and truthful.' },
      { id: 'usaha4', name: 'Perbanyak Silaturahmi', description: lang === 'id' ? 'Hubungi rekan atau kontak untuk memperkuat hubungan profesional.' : 'Connect with a colleague or contact to strengthen professional ties.' },
    ],
    dos: lang === 'id' ? ["Memulai hari lebih awal", "Bekerja dengan niat ibadah", "Menjaga kualitas dan profesionalisme", "Membangun jaringan (silaturahmi)"] : ["Starting the day early", "Working with the intention of worship", "Maintaining quality and professionalism", "Building a network (silaturahmi)"],
    donts: lang === 'id' ? ["Menunda-nunda pekerjaan", "Melakukan cara yang haram", "Mudah menyerah saat gặp kesulitan", "Memutus tali silaturahmi"] : ["Procrastinating", "Using forbidden means", "Giving up easily during difficulties", "Breaking ties of kinship"],
    skillBooster: [{ title: "Teknik Pomodoro", description: lang === 'id' ? "Kerjakan tugas selama 25 menit, lalu istirahat 5 menit. Ulangi 4 kali." : "Work for 25 minutes, then rest for 5. Repeat 4 times." }],
    reflectionPrompt: lang === 'id' ? "Apakah usaha saya hari ini sudah maksimal dan diiringi niat yang benar?" : "Has my effort today been maximum and accompanied by the right intention?"
  },
  {
    id: 'tawakal',
    name: lang === 'id' ? 'Tawakal' : 'Trust in Allah',
    emoji: '🕊️',
    description: lang === 'id' ? 'Rezeki melalui penyerahan diri sepenuhnya kepada Allah setelah melakukan usaha terbaik.' : 'Rezeki through complete reliance on Allah after making an effort.',
    dalil: lang === 'id' ? '“Dan barangsiapa yang bertawakal kepada Allah niscaya Allah akan mencukupkan (keperluan)nya.” (QS. At-Talaq: 3)' : '“And whoever relies upon Allah – then He is sufficient for him.” (Quran 65:3)',
    kisah: lang === 'id' ? 'Rasulullah SAW dan Abu Bakar bersembunyi di Gua Tsur saat Hijrah, memasrahkan perlindungan sepenuhnya kepada Allah.' : 'Prophet Muhammad (PBUH) and Abu Bakr hiding in the cave of Thawr during the Hijra, putting their complete trust in Allah\'s protection.',
    color: 'amber',
    amalan: [
      { id: 'tawakal1', name: lang === 'id' ? 'Dzikir Tawakal' : 'Recite Dua of Tawakal', description: lang === 'id' ? 'Ucapkan "Hasbunallah wa ni\'mal wakil" (Cukuplah Allah bagi kami dan Dia adalah sebaik-baik penjaga).' : 'Say "Hasbunallah wa ni\'mal wakil" (Allah is sufficient for us, and He is the best Disposer of affairs).' },
      { id: 'tawakal2', name: lang === 'id' ? 'Lepaskan Kekhawatiran' : 'Let go of a worry', description: lang === 'id' ? 'Identifikasi satu kekhawatiran dan secara sadar pasrahkan kepada Allah.' : 'Identify one worry and consciously entrust it to Allah.' },
      { id: 'tawakal3', name: lang === 'id' ? 'Shalat Dhuha' : 'Perform Shalat Dhuha', description: lang === 'id' ? 'Shalat sunnah di pagi hari yang dikenal sebagai pembuka pintu rezeki.' : 'The mid-morning prayer is known to be a practice for sustenance.' },
    ],
    dos: lang === 'id' ? ["Melakukan usaha terbaik terlebih dahulu", "Berdoa sebelum dan sesudah berusaha", "Menerima hasil dengan lapang dada"] : ["Making the best effort first", "Praying before and after effort", "Accepting results gracefully"],
    donts: lang === 'id' ? ["Pasrah tanpa berusaha", "Terlalu khawatir akan hasil", "Menyalahkan takdir jika gagal"] : ["Giving up without effort", "Worrying too much about results", "Blaming fate if failing"],
    skillBooster: [{ title: lang === 'id' ? "Latihan Melepas Kendali" : "Control Releasing Exercise", description: lang === 'id' ? "Identifikasi satu kekhawatiran. Ucapkan 'Saya serahkan urusan ini kepada-Mu, ya Allah'." : "Identify one worry. Say 'I entrust this matter to You, O Allah'." }],
    reflectionPrompt: lang === 'id' ? "Di momen mana hari ini saya benar-benar berserah diri pada Allah setelah berusaha?" : "In which moment today did I truly surrender to Allah after putting in effort?"
  },
  {
    id: 'istighfar',
    name: lang === 'id' ? 'Istighfar' : 'Repentance',
    emoji: '💧',
    description: lang === 'id' ? 'Rezeki melalui taubat. Memohon ampun membersihkan dosa yang mungkin menghambat berkah.' : 'Rezeki through repentance. Seeking forgiveness cleanses sins that may block blessings.',
    dalil: lang === 'id' ? '"Mohonlah ampun kepada Tuhanmu, sesungguhnya Dia adalah Maha Pengampun, niscaya Dia akan mengirimkan hujan kepadamu dengan lebat, dan membanyakkan harta dan anak-anakmu..." (QS. Nuh: 10-12)' : '"Ask forgiveness of your Lord. Indeed, He is ever a Perpetual Forgiver. He will send [rain from] the sky upon you in [continuing] showers and give you increase in wealth and children..." (Quran 71:10-12)',
    kisah: lang === 'id' ? 'Saran Imam Hasan al-Basri kepada banyak orang dengan berbagai masalah (kemarau, kemiskinan, kemandulan) adalah sama: "Beristighfarlah kepada Allah."' : 'The advice of Imam Hasan al-Basri to different people with different problems was the same: "Seek forgiveness from Allah."',
    color: 'indigo',
    amalan: [
      { id: 'istighfar1', name: lang === 'id' ? 'Istighfar 100x' : 'Istighfar 100x', description: lang === 'id' ? 'Ucapkan "Astaghfirullah" (Aku memohon ampun kepada Allah) 100 kali.' : 'Say "Astaghfirullah" (I seek forgiveness from Allah) 100 times.' },
      { id: 'istighfar2', name: lang === 'id' ? 'Refleksi dan Taubat' : 'Reflect and repent', description: lang === 'id' ? 'Pikirkan satu kesalahan dan mintalah ampunan dengan tulus.' : 'Think of a specific mistake and sincerely ask for forgiveness.' },
      { id: 'istighfar3', name: lang === 'id' ? 'Maafkan Orang Lain' : 'Forgive someone', description: lang === 'id' ? 'Lepaskan dendam yang kamu simpan terhadap orang lain.' : 'Let go of a grudge you hold against someone else.' },
    ],
    dos: lang === 'id' ? ["Menyesali dosa yang dilakukan", "Bertekad untuk tidak mengulangi", "Segera beristighfar setelah sadar berbuat salah"] : ["Regretting committed sins", "Determining not to repeat", "Instantly seeking forgiveness after realizing a mistake"],
    donts: lang === 'id' ? ["Menganggap remeh dosa kecil", "Menunda-nunda taubat", "Merasa putus asa dari ampunan Allah"] : ["Trivializing small sins", "Procrastinating repentance", "Feeling despair of Allah's forgiveness"],
    skillBooster: [{ title: lang === 'id' ? "Audit Dosa Harian" : "Daily Sin Audit", description: lang === 'id' ? "Sebelum tidur, luangkan 2 menit untuk mengingat kesalahan hari ini dan langsung beristighfar." : "Before bed, spend 2 minutes remembering today's mistakes and seek forgiveness immediately." }],
    reflectionPrompt: lang === 'id' ? "Kesalahan apa yang saya lakukan hari ini yang perlu saya mintakan ampunan?" : "What mistake did I make today that I need to ask for forgiveness for?"
  },
  {
    id: 'sedekah',
    name: lang === 'id' ? 'Sedekah' : 'Charity',
    emoji: '🎁',
    description: lang === 'id' ? 'Rezeki melalui berbagi. Menginfakkan harta di jalan Allah akan melipatgandakan kekayaan.' : 'Rezeki through giving. Spending in the way of Allah multiplies wealth.',
    dalil: lang === 'id' ? '"Perumpamaan orang-orang yang menafkahkan hartanya di jalan Allah adalah serupa dengan sebutir benih yang menumbuhkan tujuh bulir, pada tiap-tiap bulir seratus biji. Allah melipat gandakan (ganjaran) bagi siapa yang Dia kehendaki." (QS. Al-Baqarah: 261)' : '"The example of those who spend their wealth in the way of Allah is like a seed [of grain] which grows seven spikes; in each spike is a hundred grains. And Allah multiplies [His reward] for whom He wills." (Quran 2:261)',
    kisah: lang === 'id' ? 'Kedermawanan Utsman bin Affan yang membeli Sumur Ruma saat kemarau panjang di Madinah dan menjadikannya wakaf untuk seluruh umat Islam.' : 'The exemplary generosity of Uthman bin Affan, who purchased the Well of Ruma during a severe drought and dedicated it as an endowment for all Muslims.',
    color: 'rose',
    amalan: [
      { id: 'sedekah1', name: lang === 'id' ? 'Sedekah Harta' : 'Give any amount', description: lang === 'id' ? 'Donasi sejumlah uang, besar atau kecil, untuk orang yang membutuhkan.' : 'Donate any amount, big or small, to a person or cause.' },
      { id: 'sedekah2', name: lang === 'id' ? 'Tersenyum' : 'Smile at someone', description: lang === 'id' ? 'Senyummu kepada saudaramu adalah sedekah.' : 'Even a smile is a form of charity.' },
      { id: 'sedekah3', name: lang === 'id' ? 'Tolong Sesama' : 'Help someone in need', description: lang === 'id' ? 'Berikan waktu atau tenagamu untuk membantu orang lain.' : 'Offer your time or effort to assist someone.' },
      { id: 'sedekah4', name: 'Berbagi ilmu atau skill', description: lang === 'id' ? 'Ajarkan atau bagi sesuatu yang bermanfaat bagi orang lain.' : 'Teach or share something useful with another person.' },
    ],
    dos: lang === 'id' ? ["Memberi dengan ikhlas", "Mendahulukan yang paling membutuhkan", "Memberi dari harta yang kita cintai", "Merahasiakan sedekah sunnah"] : ["Giving sincerely", "Prioritizing those most in need", "Giving from what we love", "Keeping voluntary charity secret"],
    donts: lang === 'id' ? ["Mengungkit-ungkit pemberian", "Riya' (pamer) saat bersedekah", "Menyakiti perasaan penerima"] : ["Reminding people of your gift", "Showing off (Riya')", "Hurting the recipient's feelings"],
    skillBooster: [{ title: lang === 'id' ? "Tantangan Sedekah Tak Terlihat" : "Invisible Charity Challenge", description: lang === 'id' ? "Lakukan satu sedekah hari ini tanpa ada seorang pun yang tahu selain Allah." : "Perform one charity today without anyone knowing except Allah." }],
    reflectionPrompt: lang === 'id' ? "Peluang sedekah apa yang saya temui (atau lewatkan) hari ini?" : "What charity opportunity did I encounter (or miss) today?"
  },
  {
    id: 'anak',
    name: lang === 'id' ? 'Anak' : 'Children',
    emoji: '👶',
    description: lang === 'id' ? 'Rezeki melalui anak, yang merupakan berkah dan ujian yang dapat membukakan pintu rezeki.' : 'Rezeki through children, who are a blessing and a test from Allah that can open doors of provision.',
    dalil: lang === 'id' ? '"...dan membanyakkan harta dan anak-anakmu dan mengadakan untukmu kebun-kebun dan mengadakan (pula di dalamnya) untukmu sungai-sungai." (QS. Nuh: 12)' : '"...and give you increase in wealth and children and provide for you gardens and provide for you rivers." (Quran 71:12)',
    kisah: lang === 'id' ? 'Kisah Nabi Zakariya AS yang sudah lanjut usia dan istrinya mandul. Beliau berdoa kepada Allah dan dianugerahi Nabi Yahya AS.' : 'The story of Prophet Zakariya (Zechariah), who was old and his wife was barren. He prayed to Allah and was blessed with Prophet Yahya (John).',
    color: 'teal',
    amalan: [
      { id: 'anak1', name: 'Doa untuk Anak', description: lang === 'id' ? 'Doakan keshalihan dan masa depan anak-anakmu secara spesifik.' : 'Make a specific prayer for your childrens\' piety and future.' },
      { id: 'anak2', name: 'Ajarkan Nilai Islam', description: lang === 'id' ? 'Ajarkan satu nilai atau kisah Islam sederhana kepada anak hari ini.' : 'Teach one simple Islamic value or story to your child today.' },
      { id: 'anak3', name: 'Waktu Berkualitas', description: lang === 'id' ? 'Luangkan 15 menit waktu fokus dan tanpa distraksi bersama anak.' : 'Spend 15 minutes of focused, distraction-free time with your child.' },
    ],
    dos: lang === 'id' ? ["Mendidik dengan kasih sayang", "Memberi teladan yang baik", "Bersikap adil di antara anak-anak"] : ["Educating with love", "Giving a good example", "Being fair among children"],
    donts: lang === 'id' ? ["Memarahi di depan umum", "Membanding-bandingkan dengan orang lain", "Mendoakan keburukan saat marah"] : ["Scolding in public", "Comparing with others", "Praying for bad things when angry"],
    skillBooster: [{ title: lang === 'id' ? "Latihan Mendengar Aktif" : "Active Listening Exercise", description: lang === 'id' ? "Saat anak berbicara, dengarkan sepenuhnya tanpa menyela." : "When the child speaks, listen fully without interrupting." }],
    reflectionPrompt: lang === 'id' ? "Bagaimana interaksi saya dengan anak saya hari ini bisa memperkuat ikatan kami karena Allah?" : "How could my interaction with my child today strengthen our bond for Allah's sake?"
  },
  {
    id: 'nikah',
    name: lang === 'id' ? 'Nikah' : 'Marriage',
    emoji: '💍',
    description: lang === 'id' ? 'Rezeki melalui pernikahan. Allah berjanji akan memampukan mereka yang menikah untuk menjaga kesucian diri.' : 'Rezeki through marriage. Allah promises to enrich those who marry to protect their chastity.',
    dalil: lang === 'id' ? '"Dan kawinkanlah orang-orang yang sendirian diantara kamu... Jika mereka miskin Allah akan memampukan mereka dengan kurnia-Nya." (QS. An-Nur: 32)' : '"And marry the unmarried among you... If they should be poor, Allah will enrich them from His bounty." (Quran 24:32)',
    kisah: lang === 'id' ? 'Pernikahan Rasulullah SAW dengan Khadijah RA yang memberikan ketenangan, dukungan, dan stabilitas finansial dalam menjalankan misi dakwah.' : 'The marriage of Prophet Muhammad (PBUH) to Khadijah (RA), which brought him comfort, support, and financial stability.',
    color: 'fuchsia',
    amalan: [
      { id: 'nikah1', name: lang === 'id' ? 'Puji Pasangan' : 'Compliment your spouse', description: lang === 'id' ? 'Berikan pujian yang tulus kepada pasanganmu.' : 'Share a sincere compliment with your spouse.' },
      { id: 'nikah2', name: lang === 'id' ? 'Makan Bersama' : 'Share a meal together', description: lang === 'id' ? 'Makan bersama pasangan tanpa gangguan gawai atau TV.' : 'Eat a meal together with your spouse without distractions.' },
      { id: 'nikah3', name: 'Make Dua for your family', description: lang === 'id' ? 'Berdoa untuk keberkahan dan kebahagiaan keluargamu.' : 'Pray for the prosperity and happiness of your family.' },
      { id: 'nikah4', name: 'Bantu pasangan tanpa diminta', description: lang === 'id' ? 'Secara proaktif bantu pasangan melakukan pekerjaan rumah.' : 'Proactively help your spouse with a chore or task.' },
    ],
    dos: lang === 'id' ? ["Menjaga pandangan dan perkataan", "Bersikap lembut kepada pasangan", "Bekerja sama dalam urusan rumah tangga"] : ["Guarding gaze and speech", "Being gentle to spouse", "Cooperating in household matters"],
    donts: lang === 'id' ? ["Menceritakan aib pasangan", "Bersikap kasar dan tidak menghargai", "Membandingkan pasangan dengan orang lain"] : ["Revealing spouse's secrets", "Being rude or disrespectful", "Comparing spouse with others"],
    skillBooster: [{ title: "5 Menit Waktu Berkualitas", description: lang === 'id' ? "Luangkan 5 menit setiap hari untuk berbicara dengan pasangan tanpa gangguan." : "Spend 5 minutes each day talking with your spouse without distractions." }],
    reflectionPrompt: lang === 'id' ? "Kebaikan apa yang telah pasangan saya lakukan hari ini yang pantas saya syukuri?" : "What good deed did my spouse do today that I should be grateful for?"
  },
  {
    id: 'dijamin',
    name: lang === 'id' ? 'Dijamin' : 'Guaranteed',
    emoji: '🌍',
    description: lang === 'id' ? 'Rezeki dasar yang dijamin oleh Allah untuk setiap makhluk hidup, dari kebutuhan pokok hingga kehidupan itu sendiri.' : 'The fundamental rezeki guaranteed by Allah to every living creature, from basic sustenance to life itself.',
    dalil: lang === 'id' ? '"Dan tidak ada suatu binatang melata pun di bumi melainkan Allah-lah yang memberi rezekinya..." (QS. Hud: 6)' : '"And there is no creature on earth but that upon Allah is its provision, and He knows its place of dwelling and place of storage. All is in a clear register." (Quran 11:6)',
    kisah: lang === 'id' ? 'Kisah Maryam yang mendapati rezeki dari Allah di mihrabnya secara ajaib dari sumber yang tidak terduga.' : 'The story of Maryam (Mary) who found provisions from Allah in her prayer niche mircolously.',
    color: 'slate',
    amalan: [
      { id: 'dijamin1', name: lang === 'id' ? 'Amati Alam' : 'Observe nature', description: lang === 'id' ? 'Renungkan bagaimana Allah memberi makan burung, semut, dan makhluk lainnya.' : 'Reflect on how Allah provides for birds, ants, and other creatures.' },
      { id: 'dijamin2', name: lang === 'id' ? 'Makan dengan Sadar' : 'Eat mindfully', description: lang === 'id' ? 'Makanlah dengan kesadaran bahwa ini adalah rezeki langsung dari Allah.' : 'Eat your meal with awareness that it is a direct provision from Allah.' },
      { id: 'dijamin3', name: 'Read Surah Al-Waqi\'ah', description: lang === 'id' ? 'Surah yang dikenal sebagai pembuka pintu kekayaan.' : 'This chapter is known as the Surah of wealth.' },
    ],
    dos: lang === 'id' ? ["Meyakini jaminan rezeki dari Allah", "Mengkonsumsi yang halal dan baik", "Tidak berlebihan dalam konsumsi"] : ["Believing in Allah's guarantee", "Consuming what is halal and good", "Not over-consuming"],
    donts: lang === 'id' ? ["Takut miskin secara berlebihan", "Menghalalkan segala cara demi rezeki", "Kikir terhadap rezeki yang didapat"] : ["Extreme fear of poverty", "Using any means for wealth", "Being stingy with received rezeki"],
    skillBooster: [{ title: lang === 'id' ? "Observasi Makhluk Allah" : "Allah's Creatures Observation", description: lang === 'id' ? "Perhatikan seekor burung. Renungkan bagaimana Allah menjamin rezeki mereka." : "Observe a bird. Reflect on how Allah guarantees their provision." }],
    reflectionPrompt: lang === 'id' ? "Bagaimana saya melihat campur tangan Allah dalam rezeki mendasar saya hari ini?" : "How do I see Allah's intervention in my basic rezeki today?"
  },
];

export const getAllRewards = (lang: 'id' | 'en'): Reward[] => [
  // STREAK REWARDS
  {
    id: 'streak_istighfar_3',
    name: lang === 'id' ? 'Istighfar Konsisten' : 'Consistent Repentance',
    description: lang === 'id' ? 'Selesaikan amalan "Istighfar 100x" selama 3 hari berturut-turut.' : 'Complete "Istighfar 100x" for 3 consecutive days.',
    icon: '🥉',
    type: 'streak',
    amalId: 'istighfar1',
    target: 3,
  },
  {
    id: 'streak_istighfar_7',
    name: lang === 'id' ? 'Pejuang Istighfar' : 'Istighfar Warrior',
    description: lang === 'id' ? 'Selesaikan amalan "Istighfar 100x" selama 7 hari berturut-turut.' : 'Complete "Istighfar 100x" for 7 consecutive days.',
    icon: '🔥',
    type: 'streak',
    amalId: 'istighfar1',
    target: 7,
  },
  {
    id: 'streak_dhuha_5',
    name: lang === 'id' ? 'Dhuha Regular' : 'Daily Dhuha',
    description: lang === 'id' ? 'Laksanakan Shalat Dhuha selama 5 hari berturut-turut.' : 'Perform Shalat Dhuha for 5 consecutive days.',
    icon: '☀️',
    type: 'streak',
    amalId: 'tawakal3',
    target: 5,
  },
  {
    id: 'streak_syukur_3',
    name: lang === 'id' ? 'Hati Bersyukur' : 'Grateful Heart',
    description: lang === 'id' ? 'Selesaikan "Reflect on 3 blessings" selama 3 hari berturut-turut.' : 'Complete "Reflect on 3 blessings" for 3 consecutive days.',
    icon: '💖',
    type: 'streak',
    amalId: 'syukur2',
    target: 3,
  },
  // COMPLETION REWARDS
  {
    id: 'complete_syukur_day',
    name: lang === 'id' ? 'Ahli Syukur Harian' : 'Daily Gratitude Expert',
    description: lang === 'id' ? 'Selesaikan semua amalan di Pintu Syukur dalam satu hari.' : 'Complete all deeds in the Gate of Gratitude in one day.',
    icon: '🌟',
    type: 'completion',
    gateId: 'syukur',
    target: 4,
  },
  {
    id: 'complete_usaha_day',
    name: lang === 'id' ? 'Ikhtiar Maksimal' : 'Maximum Effort',
    description: lang === 'id' ? 'Selesaikan semua amalan di Pintu Usaha & Ikhtiar dalam satu hari.' : 'Complete all deeds in the Gate of Effort in one day.',
    icon: '🚀',
    type: 'completion',
    gateId: 'usaha',
    target: 4,
  },
  {
    id: 'complete_tawakal_day',
    name: lang === 'id' ? 'Hati yang Tenang' : 'Peaceful Heart',
    description: lang === 'id' ? 'Selesaikan semua amalan di Pintu Tawakal dalam satu hari.' : 'Complete all deeds in the Gate of Trust in one day.',
    icon: '🏞️',
    type: 'completion',
    gateId: 'tawakal',
    target: 3,
  },
  {
    id: 'complete_sedekah_day',
    name: lang === 'id' ? 'Dermawan Sejati' : 'True Philanthropist',
    description: lang === 'id' ? 'Selesaikan semua amalan di Pintu Sedekah dalam satu hari.' : 'Complete all deeds in the Gate of Charity in one day.',
    icon: '💎',
    type: 'completion',
    gateId: 'sedekah',
    target: 4,
  },
  {
    id: 'perfect_day',
    name: lang === 'id' ? 'Hari Sempurna' : 'Perfect Day',
    description: lang === 'id' ? 'Selesaikan semua amalan (non-kustom) dalam satu hari.' : 'Complete all non-custom deeds in one day.',
    icon: '💯',
    type: 'completion',
    target: 29, // Matches total amalan
  },
  {
    id: 'aktivator_8_pintu',
    name: lang === 'id' ? 'Aktivator 8 Pintu' : '8 Gates Activator',
    description: lang === 'id' ? 'Selesaikan minimal satu amalan dari setiap 8 Pintu Rezeki dalam satu hari.' : 'Complete at least one deed from each of the 8 Doors of Rizq in one day.',
    icon: '🚪',
    type: 'completion',
    target: 8,
  },
  // MILESTONE REWARDS
  {
    id: 'first_journal',
    name: lang === 'id' ? 'Jejak Pertama' : 'First Step',
    description: lang === 'id' ? 'Tulis entri pertama di Jurnal Rezeki.' : 'Write your first entry in the Rizq Journal.',
    icon: '✍️',
    type: 'milestone',
    target: 1,
  },
  {
    id: 'journal_10_entries',
    name: lang === 'id' ? 'Refleksi Mendalam' : 'Deep Reflection',
    description: lang === 'id' ? 'Tulis 10 entri di Jurnal Rezeki.' : 'Write 10 entries in the Rizq Journal.',
    icon: '📚',
    type: 'milestone',
    target: 10,
  },
  {
    id: 'first_custom_amal',
    name: lang === 'id' ? 'Inisiator Kebaikan' : 'Goodness Initiator',
    description: lang === 'id' ? 'Tambah amalan kustom pertamamu.' : 'Add your first custom deed.',
    icon: '💡',
    type: 'milestone',
    target: 1,
  },
  // CHALLENGE REWARDS
  {
    id: 'challenge_gratitude_7_day',
    name: lang === 'id' ? 'Bintang Syukur' : 'Gratitude Star',
    description: lang === 'id' ? 'Selesaikan Tantangan Syukur 7 Hari.' : 'Complete the 7-Day Gratitude Challenge.',
    icon: '🌠',
    type: 'challenge',
    target: 1,
  },
  {
    id: 'challenge_istighfar_5_day',
    name: lang === 'id' ? 'Pembersih Diri' : 'Self Purifier',
    description: lang === 'id' ? 'Selesaikan Tantangan Maraton Istighfar 5 Hari.' : 'Complete the 5-Day Istighfar Marathon.',
    icon: '✨',
    type: 'challenge',
    target: 1,
  },
  {
    id: 'challenge_sedekah_5_day',
    name: lang === 'id' ? 'Tangan di Atas' : 'Upper Hand',
    description: lang === 'id' ? 'Selesaikan Tantangan Gerakan Sedekah 5 Hari.' : 'Complete the 5-Day Charity Movement Challenge.',
    icon: '🤲',
    type: 'challenge',
    target: 1,
  },
  {
    id: 'challenge_tawakal_kickstarter_5_day',
    name: lang === 'id' ? 'Sang Muhsin' : 'The Muhsin',
    description: lang === 'id' ? 'Selesaikan Tantangan Tawakal Kickstarter 5 Hari.' : 'Complete the 5-Day Tawakal Kickstarter.',
    icon: '🕊️',
    type: 'challenge',
    target: 1,
  },
  {
    id: 'challenge_spiritual_detox_7_day',
    name: lang === 'id' ? 'Hati yang Murni' : 'Pure Heart',
    description: lang === 'id' ? 'Selesaikan Tantangan Spiritual Detox 7 Hari.' : 'Complete the 7-Day Spiritual Detox.',
    icon: '💖',
    type: 'challenge',
    target: 1,
  },
];

export const getAllChallenges = (lang: 'id' | 'en'): Challenge[] => [
    {
        id: 'gratitude_7_day',
        name: lang === 'id' ? 'Tantangan Syukur 7 Hari' : '7-Day Gratitude Challenge',
        description: lang === 'id' ? 'Latih diri untuk menjadi hamba yang bersyukur dengan menyelesaikan semua amalan di Pintu Syukur setiap hari selama seminggu penuh.' : 'Train yourself to be a grateful servant by completing all deeds in the Gate of Gratitude every day for a full week.',
        durationDays: 7,
        rewardId: 'challenge_gratitude_7_day',
        gateId: 'syukur',
        amalIds: ['syukur1', 'syukur2', 'syukur3', 'syukur4'],
    },
    {
        id: 'istighfar_5_day',
        name: lang === 'id' ? 'Maraton Istighfar 5 Hari' : '5-Day Istighfar Marathon',
        description: lang === 'id' ? 'Fokus membersihkan diri dengan melakukan "Istighfar 100x" dan "Reflect and repent" setiap hari selama 5 hari berturut-turut.' : 'Focus on purifying yourself by doing "Istighfar 100x" and "Reflect and repent" every day for 5 consecutive days.',
        durationDays: 5,
        rewardId: 'challenge_istighfar_5_day',
        gateId: 'istighfar',
        amalIds: ['istighfar1', 'istighfar2'],
    },
    {
        id: 'sedekah_5_day',
        name: lang === 'id' ? 'Gerakan Sedekah 5 Hari' : '5-Day Charity Movement',
        description: lang === 'id' ? 'Latih kedermawanan dengan memberikan sedekah (jumlah berapapun) setiap hari selama 5 hari berturut-turut.' : 'Train generosity by giving charity (any amount) every day for 5 consecutive days.',
        durationDays: 5,
        rewardId: 'challenge_sedekah_5_day',
        gateId: 'sedekah',
        amalIds: ['sedekah1'],
    },
    {
        id: 'tawakal_kickstarter_5_day',
        name: lang === 'id' ? 'Tawakal Kickstarter' : 'Tawakal Kickstarter',
        description: lang === 'id' ? 'Perkuat iman dan penyerahan diri dengan shalat Dhuha dan melepaskan satu kekhawatiran setiap hari selama 5 hari.' : 'Strengthen faith and surrender with Dhuha prayer and letting go of one worry every day for 5 days.',
        durationDays: 5,
        rewardId: 'challenge_tawakal_kickstarter_5_day',
        gateId: 'tawakal',
        amalIds: ['tawakal2', 'tawakal3'],
    },
    {
        id: 'spiritual_detox_7_day',
        name: lang === 'id' ? 'Spiritual Detox' : 'Spiritual Detox',
        description: lang === 'id' ? 'Bersihkan jiwa dengan kombinasi Istighfar 100x dan Sedekah setiap hari selama seminggu.' : 'Purify your soul with a combination of Istighfar 100x and Charity every day for a week.',
        durationDays: 7,
        rewardId: 'challenge_spiritual_detox_7_day',
        gateId: 'istighfar',
        amalIds: ['istighfar1', 'sedekah1'],
    }
];
